### ISSUE TITLE
HTTPS input models reference S3 inputs

### ISSUE THREAD

**Issue by renandincer** [bitmovin/bitmovin-go#27]
Looks like there are some typos in the models/inputs.go file.

At line https://github.com/bitmovin/bitmovin-go/blob/master/models/inputs.go#L202 
S3InputListData should be HTTPSInputListData.

Same issue is also on line 147, 196 and so on.
This prevents operating with HTTPS inputs using the go client.

**Comment by Tigraine** [comment]
Thanks for reporting this. I’ll have a look

**Comment by Tigraine** [comment]
Thanks for reporting. Has been fixed in latest master. 
We‘lol also tag a new release shortly.
