### ISSUE TITLE
GCS input and output services

### ISSUE THREAD

**Issue by shalabh-aggarwal** [bitmovin/bitmovin-go#3]
Input and output services for Google Cloud Storage do not exist.
They can be implemented as of now using RestService but it would be nice to have services which can be used directly.

**Comment by Tigraine** [comment]
Hi sorry for not responding earlier.. I'll try to make this happen asap.. @shalabh-aggarwal

**Comment by tike** [comment]
I'd be very interested in using this feature as well.

**Comment by Tigraine** [comment]
Hi @tike @shalabh-aggarwal This is now implemented and an example is available at https://github.com/bitmovin/bitmovin-go/blob/master/examples/create_simple_encoding_gcp_dash.go

Hope this helps. If you need any help please let me know
