### ISSUE TITLE
copyright / LICENSE

### ISSUE THREAD

**Issue by tike** [bitmovin/bitmovin-go#5]
Dear bitmovin develpoers,

please add a LICENSE file to clarify legal conditions for usage and development.

Thank you very much!

**Comment by Tigraine** [comment]
Hi @tike thanks for pointing this out. I just added the LICENSE.md file with the [MIT license](https://github.com/bitmovin/bitmovin-go/blob/master/LICENSE.md). All api-client from bitmovin are meant to be used and integrated into all different environments so we try to be as permissive as possible in our licensing. 
Thanks!
