### ISSUE TITLE
GCS authentication error

### ISSUE THREAD

**Issue by vidaoaaron** [bitmovin/bitmovin-go#8]
I'm trying GCS and I've incorrectly set the credentials (on purpose). I don't get an appropriate error message. The error returned by Create is nil, and every field in the response is nil, including status. I was confused, so I checked it out and the JSON response it's getting is:

```json
{"message":"Invalid authentication credentials"} 
```

ie. seems to be an unhandled case

**Comment by Tigraine** [comment]
Hi @vidaoaaron this has been fixed yesterday. Now all the services should return a meaningful `err` message if the call to the API failed. 

Please open another issue if you see any problems or are missing errors where you'd expect them. I'm closing this now.
